services:
  backend:
    build: .
    container_name: product-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - product-net
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: product-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - product-net

networks:
  product-net:
    driver: bridge